name: Timed-email-reminder

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 21 * * *

jobs:
  run-it:
    runs-on: ubuntu-latest
    name: build service
    steps: 
      - name: checkout main
        uses: actions/checkout@main
      - name: is reminder
        env:
          DATES: ${{ secrets.DATES }}
        run: |
          today=$(date "+%m-%d")
          echo "today is $today"

          for date in ${DATES[*]}
          do
          
          OLD_IFS="$IFS"
          IFS=":"
          arr=($date)
          IFS="$OLD_IFS"

          echo "this date is ${arr[0]}"
          
          if [ $today == ${arr[0]} ]
          then
            echo "send email"
            echo "今天是${arr[1]}，别忘记了哦~" > remind.html
            echo "ISREMIND=1" >> $GITHUB_ENV
            break
          fi
          done

          echo "ISREMIND is $ISREMIND"

      - name: send email
        if: env.ISREMIND == 1
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: Timed Email Reminder
          body: file://remind.html
          to: ${{ secrets.EMAIL }}
          from: Timed-email-reminder
          content_type: text/html